import html,json,shutil
from pathlib import Path
from playwright.sync_api import sync_playwright
out=Path('artifacts/operational-roles');out.mkdir(parents=True,exist_ok=True)
rows=[('Propietario','Control total y cuenta protegida.','Sin cambios.'),('Administrador','Clientes, cotizaciones, pedidos, abonos, producción, remisiones, agenda, ajustes y equipo.','Recepción de efectivo. Completar documentos de otros asesores dentro de sus sedes.'),('Vendedor','Clientes nuevos, cotizaciones, conversión a pedido, abonos y documentos propios.','Sin devoluciones, recepción administrativa de efectivo, usuarios ni despacho.'),('Bodega y logística','Consultar OP, registrar producción y preparar una remisión con varios muebles.','Sin cobros, ajustes financieros ni usuarios. Se conserva el alcance actual.'),('Consulta','Consultar clientes, cotizaciones, OP, abonos y remisiones.','Sin crear ni modificar operaciones.')]
body=''.join('<tr>'+''.join('<td>'+html.escape(v)+'</td>' for v in row)+'</tr>' for row in rows)
page='''<!doctype html><html lang="es"><meta charset="utf-8"><style>@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#252423;background:#f5f5f7;margin:0;padding:42px}header{border-bottom:2px solid #ae622d;padding-bottom:24px}small{color:#ae622d;letter-spacing:2px}h1{font-size:34px;font-weight:600;margin:12px 0}p{font-size:16px;line-height:1.5;color:#626269}table{border-collapse:collapse;background:white;width:100%;margin-top:26px;font-size:16px}th{text-align:left;background:#252423;color:white;padding:16px}td{padding:20px 16px;border-bottom:1px solid #e5e5e8;line-height:1.5;vertical-align:top}td:first-child{font-weight:600;width:19%}td:nth-child(2){width:43%}.proof{background:white;border-left:4px solid #ae622d;padding:16px 24px;margin-top:24px}footer{font-size:13px;color:#777;margin-top:22px}@media print{body{padding:0;background:white}h1{font-size:26px}td{padding:12px;font-size:13px}.proof,p{font-size:13px}}</style><header><small>MADDY · BY MADERARTE</small><h1>Accesos para la operación</h1><p>Propuesta para aprobación · 16 de septiembre de 2026<br>Publicar este código no modifica los permisos instalados.</p></header><table><thead><tr><th>Cargo</th><th>Trabajo permitido</th><th>Límite o responsabilidad</th></tr></thead><tbody>'''+body+'''</tbody></table><div class="proof"><strong>Recorrido verificado con datos sintéticos</strong><p>Vendedor: cotización → cliente nuevo → PDF → pedido → PDF → abono → recibo.<br>Bodega: recepción en producción → remisión con dos muebles → PDF.<br>Bloqueos: acciones no autorizadas, otras sedes y documentos de otros asesores.</p></div><footer>Cada persona conserva sus sedes autorizadas. Ninguna cuenta real ni permiso instalado fue modificado.<br>Los PDF del ensayo usan transporte simulado; esta evidencia no certifica una venta real.</footer></html>'''
(out/'matriz.html').write_text(page,encoding='utf-8')
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=shutil.which('google-chrome') or shutil.which('chromium'),headless=True)
 tab=browser.new_page(viewport={'width':1280,'height':1050},device_scale_factor=2)
 tab.set_content(page);tab.screenshot(path=str(out/'matriz.png'),full_page=True)
 tab.pdf(path=str(out/'matriz.pdf'),format='A4',landscape=True,print_background=True)
 browser.close()
