import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { resolve, relative, extname } from 'node:path';
import { pathToFileURL } from 'node:url';

const generated = new Set(['public/release.json', 'public/js/core/release.js']);
const text = new Set(['.html', '.css', '.js', '.json', '.svg', '.webmanifest', '.txt', '.toml', '']);
export function releaseId(root) {
  const files = [];
  function walk(dir) {
    for (const entry of readdirSync(resolve(root, dir), { withFileTypes: true })) {
      const path = dir + '/' + entry.name;
      if (entry.isDirectory()) walk(path);
      else if (!generated.has(path)) files.push(path);
    }
  }
  for (const dir of ['public', 'worker', 'functions']) walk(dir);
  files.push('package.json', 'package-lock.json', 'wrangler.toml');
  const hash = createHash('sha256');
  for (const file of files.sort()) {
    let content = readFileSync(resolve(root, file));
    if (text.has(extname(file))) content = Buffer.from(content.toString('utf8').replace(/\r\n/g, '\n'));
    hash.update(file + '\0' + content.length + '\0').update(content);
  }
  return hash.digest('hex').slice(0, 24);
}
export function stampRelease(root, check = false) {
  const id = releaseId(root);
  const outputs = {
    'public/release.json': JSON.stringify({ schema: 1, id }) + '\n',
    'public/js/core/release.js': '// Generated by npm run release:stamp. No customer data.\nexport const RELEASE_ID = ' + JSON.stringify(id) + ';\n'
  };
  for (const [path, content] of Object.entries(outputs)) {
    if (check) {
      if (readFileSync(resolve(root, path), 'utf8').replace(/\r\n/g, '\n') !== content) {
        throw new Error('Release marker is stale. Run npm run release:stamp and commit both generated files.');
      }
    } else writeFileSync(resolve(root, path), content);
  }
  return id;
}
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  console.log('Maddy release: ' + stampRelease(process.cwd(), process.argv.includes('--check')));
}
