import assert from 'node:assert/strict';
import {payrollCalculate,payrollDays,payrollPeriod,payrollPeriodLabel} from '../public/js/core/payroll-rules.js';
import {sandboxRuntime} from './fixtures/owner-sandbox-runtime.mjs';
const employee={start:'2025-01-01',salary:0,transport:true};
assert.equal(payrollDays('2026-02-16','2026-02-28'),15);
const first=payrollCalculate({type:'SALARIO',from:'2026-01-01',to:'2026-01-15'},employee),second=payrollCalculate({type:'SALARIO',from:'2026-01-16',to:'2026-01-31'},employee);
assert.equal(first.lines[0].calculation.basis,1750905);assert.equal(first.lines[0].calculation.factor,'15 / 30 días');assert.equal(first.lines.find(l=>l.label.includes('salud')).calculation.basis,875453);assert.equal(first.earned+second.earned,2000000);assert.equal(first.deducted,70036);
const settlement=payrollCalculate({type:'LIQUIDACION',from:'2026-01-01',to:'2026-12-31',primaFrom:'2026-07-01',benefitBase:2000000,severanceBase:2000000,vacationFrom:'2026-01-01',vacationBase:1750905,reviewed:true},employee);
assert.equal(settlement.lines.find(l=>l.label==='Intereses a las cesantías').amount,240000);
assert.throws(()=>payrollCalculate({type:'PRIMA',from:'2026-01-01',to:'2026-12-31',benefitBase:2000000,reviewed:true},employee),/semestre/);
assert.throws(()=>payrollCalculate({type:'SALARIO',from:'2026-02-01',to:'2026-02-15'},{...employee,end:'2026-01-31'}),/vinculación/);
assert.throws(()=>payrollCalculate({type:'LIQUIDACION',from:'2026-07-01',to:'2026-12-31',benefitBase:2000000,vacationFrom:'2026-07-01',vacationBase:1750905,reviewed:true,salaryPending:500000},employee),/fecha/);
const f=sandboxRuntime();let serial=0;const call=(a,p={},id='PAYROLL-TEST-'+String(++serial).padStart(8,'0'))=>f.c.routeAction_(a,p,{...f.ctx,requestId:id,session:f.c.validateSessionToken_(f.ctx.sessionToken,false)});
assert.equal(call('NOMINA_LISTAR').employees.length,0);assert.equal(f.production().tables.Nomina_Eventos,undefined);
const input={name:'Persona sintética',document:'DEMO-001',branch:'MP',role:'Asesor',start:'2026-01-01',end:'2026-12-31',contract:'Término fijo',transport:true,salary:0,sellerUid:'qa-owner'};
const e=call('NOMINA_TRABAJADOR_GUARDAR',input,'PAYROLL-EMP-00001');assert.equal(call('NOMINA_TRABAJADOR_GUARDAR',input,'PAYROLL-EMP-00001').id,e.id);
assert.throws(()=>call('NOMINA_TRABAJADOR_GUARDAR',input),/ya tiene/);
f.production().tables.Ordenes_Pedido.rows.push({Numero_OP:'MP-OP-0001',Fecha:'2026-01-10',Sede:'MP',Responsable:'qa-owner',Valor_Total:5000000,Abonado_Total:100000,Estado:'CONFIRMADA'});
assert.equal(call('NOMINA_LISTAR').commissions[0].amount,50000);
const p={type:'COMISION',from:'2026-06-01',to:'2026-06-30',employeeId:e.id,orders:['MP-OP-0001']};
let preview=call('NOMINA_PREVISUALIZAR',p);assert.equal(preview.document.net,46000);
const issuance={input:p,fingerprint:preview.fingerprint,confirmed:true};f.state.loseBatch=true;
assert.throws(()=>call('NOMINA_EMITIR',issuance,'PAYROLL-ISSUE-00001'));
const r=call('NOMINA_EMITIR',issuance,'PAYROLL-ISSUE-00001');assert.equal(r.number,'NOM-00001');assert.equal(f.c.readOrderFence_(),null);assert.equal(call('NOMINA_LISTAR').receipts.find(x=>x.id===r.id).employeeId,e.id);
assert.equal(call('NOMINA_LISTAR').commissions[0].status,'EN_COMPROBANTE');
assert.throws(()=>call('NOMINA_PREVISUALIZAR',p),/reservada/);
const cancel=call('NOMINA_ESTADO',{id:r.id,revision:r.revision,operation:'ANULAR',reason:'Prueba sintética'});
assert.equal(cancel.status,'ANULADO');assert.equal(call('NOMINA_LISTAR').commissions[0].status,'PENDIENTE');
preview=call('NOMINA_PREVISUALIZAR',p);const r2=call('NOMINA_EMITIR',{input:p,fingerprint:preview.fingerprint,confirmed:true});assert.equal(r2.number,'NOM-00002');
const paid=call('NOMINA_ESTADO',{id:r2.id,revision:r2.revision,operation:'PAGAR',date:'2026-06-30',method:'EFECTIVO',confirmed:true});assert.equal(paid.status,'PAGADO');assert.equal(call('NOMINA_LISTAR').commissions[0].status,'PAGADA');
assert.throws(()=>call('NOMINA_ESTADO',{id:paid.id,revision:paid.revision,operation:'ANULAR',reason:'No'}),/Solo puedes/);
f.production().tables.Ordenes_Pedido.rows[0].Valor_Total=4000000;assert.equal(call('NOMINA_LISTAR').commissions[0].status,'REVISAR');
const salary={employeeId:e.id,type:'SALARIO',from:'2026-06-01',to:'2026-06-15'};preview=call('NOMINA_PREVISUALIZAR',salary);call('NOMINA_EMITIR',{input:salary,fingerprint:preview.fingerprint,confirmed:true});assert.throws(()=>call('NOMINA_PREVISUALIZAR',salary),/coincide/);
assert.throws(()=>call('NOMINA_PREVISUALIZAR',{employeeId:e.id,type:'LIQUIDACION',from:'2026-01-01',to:'2026-06-30',benefitBase:2000000,vacationFrom:'2026-01-01',vacationBase:1750905,reviewed:true,salaryPending:875453,salaryPendingFrom:'2026-06-01',salaryPendingTo:'2026-06-15'}),/coincide/);
f.c.mdDrive_=()=>({getContentText:()=>JSON.stringify({shared:true,permissions:[{type:'anyone',role:'reader'}]})});assert.throws(()=>f.c.npPrivateFolder_({getId:()=> 'synthetic-folder'}),/privada/);
f.production().tables.Usuarios.rows[0].Rol='VENDEDOR';f.production().tables.Roles.rows.push({Rol:'VENDEDOR',Activo:'SI',Permisos_JSON:'["ordenes.read"]'});assert.throws(()=>call('NOMINA_LISTAR'),e=>e.appCode==='PERMISSION_DENIED');
console.log('Payroll: statutory example, 30-day periods, rounding, private permissions, employees, old commissions, manual eligibility, atomic timeout replay, reservation, cancellation, payment, changed sale and duplicate periods passed.');

const absence=payrollCalculate({type:'SALARIO',from:'2026-09-01',to:'2026-09-15',absent:2,workedDays:13,absenceReason:'Ausencia no remunerada de muestra'},employee);
assert.equal(absence.attendance.workedDays,13);assert.equal(absence.attendance.absentDays,2);
assert.equal(absence.lines.find(x=>x.label==='Días no remunerados · salario').amount,116727);
assert.equal(absence.lines.find(x=>x.label.includes('salud')).calculation.basis,758726);
assert.equal(absence.net,805969);
assert.throws(()=>payrollCalculate({type:'SALARIO',from:'2026-09-01',to:'2026-09-15',absent:2,workedDays:15,absenceReason:'Test'},employee),/sumar/);
assert.throws(()=>payrollCalculate({type:'SALARIO',from:'2026-09-01',to:'2026-09-15',absent:2},employee),/motivo/);
for(const [month,to] of [['2026-02','2026-02-28'],['2028-02','2028-02-29'],['2026-09','2026-09-30'],['2026-10','2026-10-31']]){const p=payrollPeriod(month,2);assert.equal(p.to,to);assert.equal(payrollDays(p.from,p.to),15);}
assert.equal(payrollPeriodLabel('SALARIO','2026-09-01','2026-09-15'),'Primera quincena de septiembre de 2026');
assert.equal(payrollPeriodLabel('SALARIO','2026-09-16','2026-09-20'),'Período personalizado');
assert.throws(()=>payrollPeriod('2026-13',1),/fecha/);
f.production().tables.Usuarios.rows[0].Rol='PROPIETARIO';
const beforeSettings=call('NOMINA_OBTENER',{id:r.id});
const settingsInput={year:2026,salary:1800000,transport:250000,revision:0,confirmed:true};
const config=call('NOMINA_PARAMETROS_GUARDAR',settingsInput,'PAYROLL-RATES-0001');
assert.equal(call('NOMINA_PARAMETROS_GUARDAR',settingsInput,'PAYROLL-RATES-0001').revision,config.revision);
assert.equal(call('NOMINA_LISTAR').rates[2026].salary,1800000);
assert.deepEqual(call('NOMINA_OBTENER',{id:r.id}),beforeSettings);
const configured=call('NOMINA_PREVISUALIZAR',{employeeId:e.id,type:'SALARIO',from:'2026-09-01',to:'2026-09-15'});
assert.equal(configured.document.ratesSnapshot.salary,1800000);assert.equal(configured.document.lines[0].amount,900000);
assert.throws(()=>call('NOMINA_PARAMETROS_GUARDAR',{...settingsInput,salary:1900000}),/cambiaron/);
assert.throws(()=>call('NOMINA_PARAMETROS_GUARDAR',{...settingsInput,revision:config.revision,salary:1}),/inferiores/);
const issueInput={employeeId:e.id,type:'SALARIO',from:'2026-10-01',to:'2026-10-15'};const oldPreview=call('NOMINA_PREVISUALIZAR',issueInput);
call('NOMINA_PARAMETROS_GUARDAR',{...settingsInput,revision:config.revision,salary:1900000});
assert.throws(()=>call('NOMINA_EMITIR',{input:issueInput,fingerprint:oldPreview.fingerprint,confirmed:true}),/camb|revis/i);
console.log('Payroll settings: persisted annual values, conflict/retry protection, immutable receipts, refreshed preview and explicit attendance passed.');
// Fortnight workflow: drafts are not receipts; review and payment remain distinct.
const runInput={month:'2026-11',half:'1'};
let run=call('NOMINA_QUINCENA',runInput);assert.equal(run.items.length,1);assert.equal(run.items[0].status,'POR_REVISAR');
const draftPayload={...runInput,input:run.items[0].input,revision:0};
let draft=call('NOMINA_BORRADOR_GUARDAR',draftPayload,'PAYROLL-DRAFT-0001');
assert.equal(call('NOMINA_BORRADOR_GUARDAR',draftPayload,'PAYROLL-DRAFT-0001').revision,draft.revision);
assert.equal(call('NOMINA_QUINCENA',runInput).items[0].status,'BORRADOR');
const countBefore=call('NOMINA_LISTAR').receipts.length;
assert.throws(()=>call('NOMINA_BORRADOR_GUARDAR',draftPayload),/actualizó/);
const rev=call('NOMINA_PREVISUALIZAR',draft.input);
draft=call('NOMINA_BORRADOR_GUARDAR',{...draftPayload,revision:draft.revision,reviewed:true,fingerprint:rev.fingerprint});
assert.equal(call('NOMINA_QUINCENA',runInput).items[0].status,'REVISADO');assert.equal(call('NOMINA_LISTAR').receipts.length,countBefore);
const runIssue={input:{...draft.input,_run:{...runInput,revision:draft.revision}},fingerprint:rev.fingerprint,confirmed:true,draftId:draft.id,draftRevision:draft.revision};
assert.throws(()=>call('NOMINA_EMITIR',{...runIssue,draftRevision:1}),/borrador/);
const ready=call('NOMINA_EMITIR',runIssue);assert.equal(call('NOMINA_QUINCENA',runInput).items[0].status,'EMITIDO');
assert.throws(()=>call('NOMINA_EMITIR',runIssue),/coincide/);
const paidRun=call('NOMINA_ESTADO',{id:ready.id,revision:ready.revision,operation:'PAGAR',date:'2026-11-15',method:'EFECTIVO',confirmed:true},'PAYROLL-PERIOD-PAY-001');
assert.equal(call('NOMINA_QUINCENA',runInput).items[0].status,'PAGADO');
assert.equal(call('NOMINA_ESTADO',{id:ready.id,revision:ready.revision,operation:'PAGAR',date:'2026-11-15',method:'EFECTIVO',confirmed:true},'PAYROLL-PERIOD-PAY-001').id,paidRun.id);
assert.throws(()=>call('NOMINA_ESTADO',{id:paidRun.id,revision:paidRun.revision,operation:'PAGAR',date:'2026-11-15',method:'EFECTIVO',confirmed:true}),/pendientes/);
const late=call('NOMINA_TRABAJADOR_GUARDAR',{...input,name:'Ingreso de muestra',document:'DEMO-INGRESO',start:'2026-11-10',sellerUid:''});
const partial=call('NOMINA_QUINCENA',runInput).items.find(x=>x.employee.id===late.id);assert.equal(partial.input.from,'2026-11-10');assert.equal(partial.days.periodDays,6);
const specialInput={type:'SALARIO',from:'2026-09-01',to:'2026-09-15',noveltyType:'INCAPACIDAD',noveltyDays:2,noveltyDetail:'Incapacidad de muestra 3 y 4 de septiembre',noveltyAmount:116727,noveltyBase:116727,transportDays:13,noveltyReviewed:true};
assert.throws(()=>payrollCalculate({...specialInput,noveltyReviewed:false},employee),/Revisa/);
assert.throws(()=>payrollCalculate({...specialInput,transportDays:15},employee),/auxilio/);
const sick=payrollCalculate(specialInput,employee);assert.equal(sick.attendance.absentDays,0);assert.equal(sick.lines.find(x=>x.label.includes('Incapacidad')).amount,116727);assert.equal(sick.lines.find(x=>x.label.includes('salud')).calculation.basis,875453);assert.ok(sick.notes.includes('3 y 4'));
const permit=payrollCalculate({...specialInput,noveltyType:'PERMISO'},employee);assert.equal(permit.lines[0].amount,875453);assert.equal(permit.attendance.workedDays,15);
assert.throws(()=>payrollCalculate({...specialInput,noveltyDays:16},employee),/días/);
f.production().tables.Usuarios.rows[0].Rol='VENDEDOR';assert.throws(()=>call('NOMINA_QUINCENA',runInput),e=>e.appCode==='PERMISSION_DENIED');assert.throws(()=>call('NOMINA_BORRADOR_GUARDAR',draftPayload),e=>e.appCode==='PERMISSION_DENIED');
console.log('Payroll fortnight: draft replay/conflicts, review without issuance, duplicate period/payment prevention, prorated entry, typed novelties and permissions passed.');
