import assert from 'node:assert/strict';
import {payrollCalculate,payrollDays} from '../public/js/core/payroll-rules.js';
import {sandboxRuntime} from './fixtures/owner-sandbox-runtime.mjs';
const employee={start:'2025-01-01',salary:0,transport:true};
assert.equal(payrollDays('2026-02-16','2026-02-28'),15);
const first=payrollCalculate({type:'SALARIO',from:'2026-01-01',to:'2026-01-15'},employee),second=payrollCalculate({type:'SALARIO',from:'2026-01-16',to:'2026-01-31'},employee);
assert.equal(first.earned+second.earned,2000000);assert.equal(first.deducted,70036);
const settlement=payrollCalculate({type:'LIQUIDACION',from:'2026-01-01',to:'2026-12-31',primaFrom:'2026-07-01',benefitBase:2000000,severanceBase:2000000,vacationBase:1750905,reviewed:true},employee);
assert.equal(settlement.lines.find(l=>l.label==='Intereses a las cesantías').amount,240000);
assert.throws(()=>payrollCalculate({type:'PRIMA',from:'2026-01-01',to:'2026-12-31',benefitBase:2000000,reviewed:true},employee),/semestre/);
assert.throws(()=>payrollCalculate({type:'SALARIO',from:'2026-02-01',to:'2026-02-15'},{...employee,end:'2026-01-31'}),/vinculación/);
assert.throws(()=>payrollCalculate({type:'LIQUIDACION',from:'2026-07-01',to:'2026-12-31',benefitBase:2000000,vacationBase:1750905,reviewed:true,salaryPending:500000},employee),/fecha/);
const f=sandboxRuntime();let serial=0;const call=(a,p={},id='PAYROLL-TEST-'+String(++serial).padStart(8,'0'))=>f.c.routeAction_(a,p,{...f.ctx,requestId:id,session:f.c.validateSessionToken_(f.ctx.sessionToken,false)});
assert.equal(call('NOMINA_LISTAR').employees.length,0);assert.equal(f.production().tables.Nomina_Eventos,undefined);
const input={name:'Persona sintética',document:'DEMO-001',branch:'MP',role:'Asesor',start:'2026-01-01',end:'2026-12-31',contract:'Término fijo',transport:true,salary:0,sellerUid:'qa-owner'};
const e=call('NOMINA_TRABAJADOR_GUARDAR',input,'PAYROLL-EMP-00001');assert.equal(call('NOMINA_TRABAJADOR_GUARDAR',input,'PAYROLL-EMP-00001').id,e.id);
assert.throws(()=>call('NOMINA_TRABAJADOR_GUARDAR',input),/ya tiene/);
f.production().tables.Ordenes_Pedido.rows.push({Numero_OP:'MP-OP-0001',Fecha:'2026-01-10',Sede:'MP',Responsable:'qa-owner',Valor_Total:5000000,Abonado_Total:100000,Estado:'CONFIRMADA'});
assert.equal(call('NOMINA_LISTAR').commissions[0].amount,50000);
const p={type:'COMISION',from:'2026-06-01',to:'2026-06-30',employeeId:e.id,orders:['MP-OP-0001']};
let preview=call('NOMINA_PREVISUALIZAR',p);assert.equal(preview.document.net,46000);
const issuance={input:p,fingerprint:preview.fingerprint,confirmed:true};f.state.loseBatch=true;
assert.throws(()=>call('NOMINA_EMITIR',issuance,'PAYROLL-ISSUE-00001'));
const r=call('NOMINA_EMITIR',issuance,'PAYROLL-ISSUE-00001');assert.equal(r.number,'NOM-00001');assert.equal(f.c.readOrderFence_(),null);
assert.equal(call('NOMINA_LISTAR').commissions[0].status,'EN_COMPROBANTE');
assert.throws(()=>call('NOMINA_PREVISUALIZAR',p),/reservada/);
const cancel=call('NOMINA_ESTADO',{id:r.id,revision:r.revision,operation:'ANULAR',reason:'Prueba sintética'});
assert.equal(cancel.status,'ANULADO');assert.equal(call('NOMINA_LISTAR').commissions[0].status,'PENDIENTE');
preview=call('NOMINA_PREVISUALIZAR',p);const r2=call('NOMINA_EMITIR',{input:p,fingerprint:preview.fingerprint,confirmed:true});assert.equal(r2.number,'NOM-00002');
const paid=call('NOMINA_ESTADO',{id:r2.id,revision:r2.revision,operation:'PAGAR',date:'2026-06-30',method:'EFECTIVO',confirmed:true});assert.equal(paid.status,'PAGADO');assert.equal(call('NOMINA_LISTAR').commissions[0].status,'PAGADA');
assert.throws(()=>call('NOMINA_ESTADO',{id:paid.id,revision:paid.revision,operation:'ANULAR',reason:'No'}),/Solo puedes/);
f.production().tables.Ordenes_Pedido.rows[0].Valor_Total=4000000;assert.equal(call('NOMINA_LISTAR').commissions[0].status,'REVISAR');
const salary={employeeId:e.id,type:'SALARIO',from:'2026-06-01',to:'2026-06-15'};preview=call('NOMINA_PREVISUALIZAR',salary);call('NOMINA_EMITIR',{input:salary,fingerprint:preview.fingerprint,confirmed:true});assert.throws(()=>call('NOMINA_PREVISUALIZAR',salary),/coincide/);
assert.throws(()=>call('NOMINA_PREVISUALIZAR',{employeeId:e.id,type:'LIQUIDACION',from:'2026-01-01',to:'2026-06-30',benefitBase:2000000,vacationBase:1750905,reviewed:true,salaryPending:875453,salaryPendingFrom:'2026-06-01',salaryPendingTo:'2026-06-15'}),/coincide/);
f.c.mdDrive_=()=>({getContentText:()=>JSON.stringify({shared:true,permissions:[{type:'anyone',role:'reader'}]})});assert.throws(()=>f.c.npPrivateFolder_({getId:()=> 'synthetic-folder'}),/privada/);
f.production().tables.Usuarios.rows[0].Rol='VENDEDOR';f.production().tables.Roles.rows.push({Rol:'VENDEDOR',Activo:'SI',Permisos_JSON:'["ordenes.read"]'});assert.throws(()=>call('NOMINA_LISTAR'),e=>e.appCode==='PERMISSION_DENIED');
console.log('Payroll: statutory example, 30-day periods, rounding, private permissions, employees, old commissions, manual eligibility, atomic timeout replay, reservation, cancellation, payment, changed sale and duplicate periods passed.');
