function ajDocumentPlan_(number,p,plan,event,stamp,s,requestId){
  mdSchema_();var row=plan.row,parent=mdUnique_(listRows_('Carpetas_Documentales'),'Clave',mdScope_()+':OP:'+row.Numero_OP+':MEDIA');if(!parent)throw appError_('DOCUMENT_NOT_PLANNED','Completa la documentación de la OP antes del ajuste.',409);
  var doc={documentKind:'adjustment',issued:true,number:number,orderNumber:row.Numero_OP,branchCode:row.Sede,date:stamp,advisor:s.profile.name||'',client:{name:row.Nombre_Cliente,document:String(row.Cedula_NIT)},type:p.type,amount:plan.amount,reason:p.reason,reference:p.reference,before:plan.before,after:plan.after,items:event.items,target:plan.target?{number:plan.target.Numero_OP,client:plan.target.Nombre_Cliente,document:String(plan.target.Cedula_NIT),before:plan.targetBefore,after:plan.targetAfter}:null};
  if(typeof osActive_==='function'&&osActive_())doc.sandbox=OWNER_SANDBOX_CONTEXT_.id;
  var slot={Archivo_ID:number+'-PDF-V1',Numero_OP:row.Numero_OP,Tipo:'AJUSTE',Nombre:number+'.pdf',Mime_Type:'application/pdf',File_ID:mdIds_(1)[0],Parent_ID:parent.File_ID,Estado:'PENDIENTE',Version:1,Creado_Por:s.profile.uid,Request_ID:requestId,Fecha_Registro:stamp,Plan_JSON:JSON.stringify(doc)};
  var documents=[row.Numero_OP].concat(plan.target?[plan.target.Numero_OP]:[]).map(function(op,i){return {ID_Documento:slot.Archivo_ID+(i?'-DESTINO':''),Tipo_Documento:'AJUSTE',Numero_Relacionado:op,Cedula_NIT:i?plan.target.Cedula_NIT:row.Cedula_NIT,Nombre_Cliente:i?plan.target.Nombre_Cliente:row.Nombre_Cliente,Nombre_Archivo:slot.Nombre,File_ID:slot.File_ID,Mime_Type:slot.Mime_Type,Version:1,Activo:'NO',Fecha_Registro:stamp,Operador:s.profile.uid,Request_ID:requestId};});
  return [orderAppendRequest_('Archivos_Orden',[slot]),orderAppendRequest_('Documentos',documents),orderAppendRequest_('Versiones_Documentos',[{Version_ID:slot.Archivo_ID,Tipo_Documento:'AJUSTE',Numero_Relacionado:number,Version:1,Activo:'NO',File_ID:slot.File_ID,Nombre_Archivo:slot.Nombre,Generado_Por:s.profile.uid,Request_ID:requestId}])];
}
function ajDocumentAccess_(number,context){var s=ajSession_(context,false),r=mdUnique_(listRows_('Anulaciones'),'Anulacion_ID',number);if(!r||r.Tipo_Entidad!=='AJUSTE_OP'||r.Estado!=='CONFIRMADA')throw appError_('ADJUSTMENT_NOT_FOUND','No se encontró el ajuste.',404);var e=parseJson_(r.Consecuencias_JSON,null),source=findRow_('Ordenes_Pedido','Numero_OP',r.Entidad_ID),target=e&&e.target?findRow_('Ordenes_Pedido','Numero_OP',e.target):null;if(!source||(!orderBranchReadable_(s,source.Sede)||(target&&!orderBranchReadable_(s,target.Sede))))throw appError_('BRANCH_NOT_ALLOWED','No tienes acceso a este ajuste.',403);var slot=mdUnique_(mdRows_(r.Entidad_ID),'Archivo_ID',number+'-PDF-V1');if(!slot)throw appError_('DOCUMENT_NOT_PLANNED','Falta el documento reservado del ajuste.',409);return {slot:slot};}
function ajPreparePdf_(payload,context){mdInternal_(context);ajSession_(context,true);return mdLocked_(function(){var a=ajDocumentAccess_(payload.number,context);if(a.slot.Estado==='LISTO'){mdDownload_(a.slot);return {number:payload.number,complete:true};}return {number:payload.number,complete:false,id:a.slot.Archivo_ID,planHash:sha256_(a.slot.Plan_JSON),document:parseJson_(a.slot.Plan_JSON,null)};});}
function ajConfirmPdf_(payload,context){mdInternal_(context);ajSession_(context,true);return mdLocked_(function(){var slot=ajDocumentAccess_(payload.number,context).slot;if(slot.Archivo_ID!==payload.id||sha256_(slot.Plan_JSON)!==payload.planHash)throw appError_('DOCUMENT_REVISION_CHANGED','El ajuste no coincide con su documento.',409);var bytes=mdDecode_(payload.base64,ORDER_MEDIA_LIMITS_.pdfBytes);if(!mdMagic_(bytes,'application/pdf'))throw appError_('PDF_INVALID','El archivo no es un PDF.',400);var stored=mdStore_(slot,bytes),version=mdUnique_(listRows_('Versiones_Documentos'),'Version_ID',slot.Archivo_ID);if(!version)ajFail_();var requests=mdReadyRequests_(slot,stored).concat(orderUpdateRequests_('Versiones_Documentos',version._row,{Activo:'SI',URL:mdFileUrl_(slot.File_ID),Hash_SHA256:mdBytesHash_(stored),Fecha_Generacion:now_().toISOString()}));listRows_('Documentos').filter(function(d){return d.File_ID===slot.File_ID;}).forEach(function(d){requests=requests.concat(orderUpdateRequests_('Documentos',d._row,{Activo:'SI',URL:mdFileUrl_(slot.File_ID),Hash_SHA256:mdBytesHash_(stored)}));});orderAtomicBatch_(requests);return {number:payload.number,complete:true};});}
function ajReadPdf_(payload,context){var slot=ajDocumentAccess_(payload.number,context).slot;if(slot.Estado!=='LISTO')throw appError_('PDF_PENDING','El comprobante está pendiente.',409);return {name:slot.Nombre,mime:'application/pdf',base64:Utilities.base64Encode(mdDownload_(slot))};}

