// Private append-only payroll ledger. No payroll action initiates a bank transfer.
var PAYROLL_HEADERS_=['ID','Fecha','Tipo','Entidad_ID','Version','Usuario','Request_ID','Fingerprint','Datos_JSON'];
function npSession_(ctx,permission){var s=validateSessionToken_(ctx.sessionToken,false);requirePermission_(s,'nomina.read');if(permission)requirePermission_(s,permission);return s;}
function npRows_(){return getSpreadsheet_().getSheetByName('Nomina_Eventos')?listRows_('Nomina_Eventos'):[];}
function npEnsure_(){var b=getSpreadsheet_(),s=b.getSheetByName('Nomina_Eventos');if(!s){s=b.insertSheet('Nomina_Eventos');s.getRange(1,1,1,PAYROLL_HEADERS_.length).setValues([PAYROLL_HEADERS_]);SpreadsheetApp.flush();}if(getHeaders_(s).join('|')!==PAYROLL_HEADERS_.join('|'))throw appError_('PAYROLL_SCHEMA','Revisa el registro de nómina.',503);}
function npState_(rows){var state={employees:{},receipts:{},files:{}};rows.forEach(function(r){var d=parseJson_(r.Datos_JSON,null);if(!d)throw appError_('PAYROLL_INTEGRITY','Un registro de nómina necesita revisión.',409);var group=r.Tipo==='TRABAJADOR'?state.employees:r.Tipo==='ARCHIVO'?state.files:state.receipts;group[r.Entidad_ID]=d;});return state;}
function npText_(v,max){return String(v==null?'':v).trim().slice(0,max||160);}
function npReceipt_(st,id){var d=st.receipts[id];if(!d)throw appError_('PAYROLL_NOT_FOUND','No se encontró el comprobante.',404);return d;}
function npEmployee_(st,id){var e=st.employees[id];if(!e)throw appError_('PAYROLL_EMPLOYEE','Selecciona un trabajador registrado.',404);return e;}
function npCommissionRows_(st){
  var reserved={};Object.values(st.receipts).filter(function(r){return r.status!=='ANULADO';}).forEach(function(r){(r.commissions||[]).forEach(function(c){if(reserved[c.order])throw appError_('PAYROLL_DUPLICATE','Hay una comisión repetida que requiere revisión.',409);reserved[c.order]={receipt:r,commission:c};});});
  var users={};listRows_('Usuarios').forEach(function(u){users[u.UID_Firebase]=u.Nombre_Completo;});
  return listRows_('Ordenes_Pedido').filter(function(o){return o.Numero_OP;}).map(function(o){
    var held=reserved[o.Numero_OP],total=Number(o.Valor_Total),owner=String(o.Responsable||''),employees=Object.values(st.employees).filter(function(e){return e.sellerUid&&e.sellerUid===owner;});
    var cancelled=/ANUL|CANCEL/.test(normalizeCode_(o.Estado)),changed=held&&(held.commission.total!==total||cancelled||held.commission.owner!==owner);
    return {order:o.Numero_OP,date:valueDateIso_(o.Fecha),client:String(o.Nombre_Cliente||''),owner:owner,seller:users[owner]||owner||'Sin asesor',employeeId:employees.length===1?employees[0].id:'',total:total,paid:Number(o.Abonado_Total)||0,delivery:String(o.Estado_Entrega||o.Estado_Produccion||'Sin entrega registrada'),amount:Math.round(total/100),status:changed?'REVISAR':held?(held.receipt.status==='PAGADO'?'PAGADA':'EN_COMPROBANTE'):cancelled?'NO_APLICA':'PENDIENTE',receipt:held?held.receipt.number:'',reserved:!!held};
  }).sort(function(a,b){return a.date.localeCompare(b.date);});
}
function npList_(p,ctx){var s=npSession_(ctx),st=npState_(npRows_());return {employees:Object.values(st.employees),receipts:Object.values(st.receipts).map(function(r){return {id:r.id,number:r.number,employee:r.employee.name,type:r.type,from:r.from,to:r.to,status:r.status,net:r.net,date:r.date,revision:r.revision};}).sort(function(a,b){return b.date.localeCompare(a.date);}),commissions:npCommissionRows_(st),sellers:listRows_('Usuarios').map(function(u){return {id:String(u.UID_Firebase||''),name:String(u.Nombre_Completo||'')};}).filter(function(u){return u.id;}),rates:PAYROLL_RATES};}
function npGet_(p,ctx){npSession_(ctx);var st=npState_(npRows_());if(p.employeeId){var e=npEmployee_(st,p.employeeId);return {employee:e,files:Object.values(st.files).filter(function(f){return f.employeeId===e.id;}).map(function(f){return {id:f.id,name:f.name,date:f.date};})};}return npReceipt_(st,p.id);}
function npPreviewData_(p,st){
  var e=npEmployee_(st,p.employeeId);if(e.status!=='ACTIVO')throw Error('El trabajador está archivado.');
  var ids=p.orders||[];if(!Array.isArray(ids)||ids.length>40||new Set(ids).size!==ids.length)throw Error('Revisa la selección de ventas.');
  var all=npCommissionRows_(st),commissions=ids.map(function(id){var c=all.filter(function(x){return x.order===id;})[0];if(!c||c.status!=='PENDIENTE'||c.employeeId!==e.id)throw Error('Una comisión ya está reservada, cambió o pertenece a otro trabajador.');return c;});
  var result=payrollCalculate(p,e,commissions);result.employee=Object.assign({},e);result.employee.document=String(e.document);delete result.employee.contact;delete result.employee.address;delete result.employee.birthday;
  Object.values(st.receipts).filter(function(r){return r.status!=='ANULADO'&&r.employee.id===e.id;}).forEach(function(r){result.coverage.forEach(function(c){(r.coverage||[]).forEach(function(old){if(old.concept===c.concept&&old.from<=c.to&&old.to>=c.from)throw Error('El período de '+c.concept.toLowerCase()+' coincide con '+r.number+'. Revisa ese comprobante antes de emitir otro.');});});});
  return result;
}
function npPreview_(p,ctx){npSession_(ctx,'nomina.prepare');var d=npPreviewData_(p,npState_(npRows_()));return {document:d,fingerprint:sha256_(JSON.stringify(d))};}
function npCommit_(ctx,permission,type,make){
  var s=npSession_(ctx,permission),id=orderRequestId_(ctx.requestId),hash=sha256_(JSON.stringify(ctx.payrollPayload)),lock=osOperationLock_();if(!lock.tryLock(5000))throw appError_('PAYROLL_BUSY','Hay un guardado en curso. Reintenta el mismo registro.',503);
  try{var rows=npRows_(),old=rows.filter(function(r){return r.Request_ID===id;})[0];if(old){if(old.Usuario!==s.profile.uid||old.Fingerprint!==hash||old.Tipo!==type)throw appError_('REQUEST_ID_CONFLICT','El intento pertenece a otro contenido.',409);clearConfirmedOrderFence_();return parseJson_(old.Datos_JSON,null);}
    assertNoUnresolvedOrderFence_();var st=npState_(rows),d=make(st,s,rows);d.revision=(d.revision||0)+1;d.updatedAt=now_().toISOString();npEnsure_();
    var event={ID:Utilities.getUuid(),Fecha:d.updatedAt,Tipo:type,Entidad_ID:d.id,Version:d.revision,Usuario:s.profile.uid,Request_ID:id,Fingerprint:hash,Datos_JSON:JSON.stringify(d)};
    var audit={ID:id+'-AUD',Fecha:d.updatedAt,Usuario:s.profile.uid,Rol:s.profile.role,Modulo:'NOMINA',Accion:type,Entidad:'NOMINA',Entidad_ID:d.number||d.id,Resumen:'Actualización de nómina',Estado:'CONFIRMADA',Request_ID:id,Despues_JSON:JSON.stringify({status:d.status||'GUARDADO'}),Reversible:'NO',Motivo_No_Reversible:'Historial laboral conservado.'};
    // The same atomic batch supplies the global recovery fence with its confirmation.
    var requests=[orderAppendRequest_('Nomina_Eventos',[event]),orderAppendRequest_('Auditoria',[audit]),orderAppendRequest_('Idempotencia',[{Request_ID:id,Fecha:d.updatedAt,Tipo_Operacion:'NOMINA_'+type,Entidad:'NOMINA',Entidad_ID:d.id,Estado:'CONFIRMADA',Resultado_JSON:JSON.stringify({fingerprint:hash,result:{id:d.id,requestId:id}}),Usuario:s.profile.uid}])];
    SpreadsheetApp.flush();reserveOrderFence_(id,s.profile.uid,hash,'NOMINA_'+type);orderAtomicBatch_(requests);clearConfirmedOrderFence_();return d;
  }finally{lock.releaseLock();}
}
function npEmployeeSave_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,'nomina.workers','TRABAJADOR',function(st){
  var old=p.id?npEmployee_(st,p.id):null;if(old&&old.revision!==p.revision)throw Error('La ficha cambió. Vuelve a abrirla.');
  var e={id:old?old.id:'EMP-'+Utilities.getUuid(),revision:old?old.revision:0,name:npText_(p.name),document:npText_(p.document,40),role:npText_(p.role,80),branch:npText_(p.branch,8),start:payrollDate(p.start),end:p.end?payrollDate(p.end):'',birthday:p.birthday?payrollDate(p.birthday):'',contract:npText_(p.contract,60),contact:npText_(p.contact),address:npText_(p.address,300),salary:payrollAmount(p.salary),transport:p.transport!==false,sellerUid:npText_(p.sellerUid),status:p.status==='ARCHIVADO'?'ARCHIVADO':'ACTIVO'};
  if(!e.name||!e.document||!['MP','TP'].includes(e.branch)||!e.role||!e.contract)throw Error('Completa nombre, identificación, sede, cargo y contrato.');if(e.end&&e.end<e.start)throw Error('Revisa las fechas del contrato.');if(e.birthday&&e.birthday>=e.start)throw Error('Revisa la fecha de nacimiento.');
  if(e.salary&&e.salary<PAYROLL_RATES[2026].salary)throw Error('Para jornada completa, el salario no puede ser inferior al mínimo vigente.');
  if(Object.values(st.employees).some(function(x){return x.id!==e.id&&(x.document===e.document||e.sellerUid&&x.sellerUid===e.sellerUid);}))throw Error('La identificación o el asesor ya tiene una ficha laboral.');
  if(e.sellerUid&&!listRows_('Usuarios').some(function(u){return u.UID_Firebase===e.sellerUid;}))throw Error('Selecciona un asesor existente.');return e;
});}
function npIssue_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,'nomina.issue','EMISION',function(st,s){requirePermission_(s,'nomina.prepare');var d=npPreviewData_(p.input,st);if(sha256_(JSON.stringify(d))!==p.fingerprint)throw Error('Los datos cambiaron. Revisa nuevamente el cálculo.');if(p.confirmed!==true)throw Error('Confirma el desglose antes de emitir.');var n=Object.keys(st.receipts).length+1;d.id='NOM-'+Utilities.getUuid();d.number='NOM-'+String(n).padStart(5,'0');d.status='EMITIDO';d.date=now_().toISOString();d.issuedBy=s.profile.name;return d;});}
function npChange_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,p.operation==='PAGAR'?'nomina.pay':'nomina.issue','ESTADO',function(st,s){var d=JSON.parse(JSON.stringify(npReceipt_(st,p.id)));if(d.revision!==p.revision)throw Error('El comprobante cambió. Vuelve a abrirlo.');if(d.status!=='EMITIDO')throw Error('Solo puedes actualizar comprobantes emitidos pendientes de pago.');if(p.operation==='ANULAR'){if(!npText_(p.reason))throw Error('Indica el motivo de anulación.');d.status='ANULADO';d.reason=npText_(p.reason,500);}else if(p.operation==='PAGAR'){if(p.confirmed!==true)throw Error('Confirma que el pago ya fue realizado.');if(npCommissionRows_(st).some(function(c){return c.receipt===d.number&&c.status==='REVISAR';}))throw Error('La venta cambió. Anula el comprobante pendiente y revisa las comisiones antes de registrar el pago.');d.payment={date:payrollDate(p.date),method:npText_(p.method,40),reference:npText_(p.reference),by:s.profile.name};if(!['EFECTIVO','TRANSFERENCIA'].includes(d.payment.method))throw Error('Selecciona el medio de pago.');d.status='PAGADO';}else throw Error('Acción no válida.');return d;});}
function npPrivateFolder_(folder){var m=JSON.parse(mdDrive_('drive/v3/files/'+encodeURIComponent(folder.getId())+'?fields=trashed,shared,permissions(type,role)',{method:'get'}).getContentText());if(m.trashed||m.shared!==false||!m.permissions||m.permissions.length!==1||m.permissions[0].type!=='user'||m.permissions[0].role!=='owner')throw Error('La carpeta de nómina debe ser privada antes de guardar documentos laborales.');return folder;}
function npFolder_(employeeId,year){var parents=getDocumentsRoot_().getParents();if(!parents.hasNext())throw Error('No se encontró la raíz de Maderarte.');var root=parents.next();if(root.getName()!=='MADERARTE APP')throw Error('Revisa la raíz documental.');npPrivateFolder_(root);var folder=npPrivateFolder_(getOrCreateFolder_(root,'06_NOMINA'));var employee=npPrivateFolder_(getOrCreateFolder_(folder,sanitizeFolderName_(employeeId)));return npPrivateFolder_(getOrCreateFolder_(employee,year||'EXPEDIENTE'));}
function npFileSave_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,'nomina.workers','ARCHIVO',function(st){var e=npEmployee_(st,p.employeeId),bytes=Utilities.base64Decode(String(p.base64||''));if(bytes.length>650000||bytes.length<5||String.fromCharCode.apply(null,bytes.slice(0,5))!=='%PDF-')throw Error('Adjunta un PDF de hasta 650 KB.');var name=npText_(p.name,100).replace(/[^\w .áéíóúñÁÉÍÓÚÑ-]/g,'');if(!name.toLowerCase().endsWith('.pdf'))throw Error('Adjunta un archivo PDF.');var key='DOC-'+ctx.requestId,folder=npFolder_(e.id,''),existing=folder.getFilesByName(key+'.pdf'),f=existing.hasNext()?existing.next():folder.createFile(Utilities.newBlob(bytes,'application/pdf',key+'.pdf'));return {id:key,employeeId:e.id,fileId:f.getId(),name:name,date:now_().toISOString()};});}
function npFileRead_(p,ctx){npSession_(ctx);var st=npState_(npRows_()),f=st.files[p.id];if(!f)throw Error('No se encontró el documento.');return {name:f.name,base64:Utilities.base64Encode(DriveApp.getFileById(f.fileId).getBlob().getBytes())};}
function npPdfPlan_(p,ctx){npSession_(ctx);if(!ctx.proxyMeta.documentPipeline)throw Error('Solicitud documental no autorizada.');var d=npReceipt_(npState_(npRows_()),p.id);return {document:Object.assign({documentKind:'payroll'},d),hash:sha256_(JSON.stringify(d))};}
function npPdfSave_(p,ctx){npSession_(ctx);if(!ctx.proxyMeta.documentPipeline)throw Error('Solicitud documental no autorizada.');var lock=osOperationLock_();if(!lock.tryLock(5000))throw Error('Reintenta guardar el documento.');try{var d=npReceipt_(npState_(npRows_()),p.id);if(sha256_(JSON.stringify(d))!==p.hash)throw Error('El comprobante cambió. Genera su versión actual.');var bytes=Utilities.base64Decode(String(p.base64||''));if(bytes.length<5||bytes.length>12000000||String.fromCharCode.apply(null,bytes.slice(0,5))!=='%PDF-')throw Error('No se recibió un PDF válido.');var folder=npFolder_(d.employee.id,String(d.year)),name=d.number+'-v'+d.revision+'.pdf',existing=folder.getFilesByName(name);if(!existing.hasNext())folder.createFile(Utilities.newBlob(bytes,'application/pdf',name));return {saved:true,name:name};}finally{lock.releaseLock();}}
