// Generated from public/js/core/payroll-rules.js. Do not edit independently.
// Shared deterministic payroll rules; Apps Script mirror generated by sync-payroll-rules.mjs.
const PAYROLL_RATES = Object.freeze({2025:{salary:1423500,transport:200000},2026:{salary:1750905,transport:249095}});
function payrollDate(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v||'')||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw Error('Revisa la fecha.');return v;}
function payrollDays(from,to){payrollDate(from);payrollDate(to);if(from>to)throw Error('La fecha inicial es posterior a la final.');const a=from.split('-').map(Number),b=to.split('-').map(Number);const last=new Date(Date.UTC(b[0],b[1],0)).getUTCDate();return (b[0]-a[0])*360+(b[1]-a[1])*30+Math.min(30,b[2]===last?30:b[2])-Math.min(30,a[2])+1;}
function payrollAmount(v){const n=Number(v||0);if(!Number.isFinite(n)||n<0||n>1000000000)throw Error('Revisa los importes: usa valores positivos, sin separadores.');return Math.round(n);}
function payrollCalculate(p,employee,commissions=[]){
  const from=payrollDate(p.from),to=payrollDate(p.to),year=Number(to.slice(0,4)),rates=PAYROLL_RATES[year];
  if(!rates)throw Error('Faltan parámetros aprobados para ese año.');if(from>to||from<employee.start||(employee.end&&to>employee.end&&p.type!=='COMISION'))throw Error('El período debe estar dentro de la vinculación laboral.');
  if(!['SALARIO','COMISION','PRIMA','LIQUIDACION'].includes(p.type))throw Error('Selecciona el tipo de comprobante.');
  const salary=payrollAmount(employee.salary||rates.salary),transport=employee.transport===false?0:rates.transport,lines=[],coverage=[];
  const add=(label,value,deduction=false,calculation=null)=>{value=payrollAmount(value);if(value)lines.push({label,amount:value,deduction,calculation:calculation||{basis:value,factor:'Valor registrado'}});};
  const cover=(concept,a,b)=>coverage.push({concept,from:a,to:b});
  const commission=commissions.reduce((sum,c)=>sum+payrollAmount(c.amount),0);
  let taxable=commission;
  if(p.type==='SALARIO'){
    if(from.slice(0,7)!==to.slice(0,7))throw Error('Prepara la nómina por mes o quincena.');
    const days=payrollDays(from,to),absent=Number(p.absent||0);if(!Number.isInteger(absent)||absent<0||absent>days||days>30)throw Error('Revisa los días no remunerados.');
    const paidDays=days-absent;const secondHalf=Number(from.slice(8))===16&&days===15&&absent===0;
    const earned=secondHalf?salary-Math.round(salary/2):Math.round(salary*paidDays/30);
    const travel=secondHalf?transport-Math.round(transport/2):Math.round(transport*paidDays/30);
    add('Salario · '+paidDays+' días',earned,false,{basis:salary,factor:paidDays+' / 30 días',from,to});add('Auxilio de transporte',travel,false,{basis:transport,factor:paidDays+' / 30 días',from,to});taxable+=earned;
    add('Otros devengados salariales',p.extra);taxable+=payrollAmount(p.extra);cover('SALARIO',from,to);
  }
  if(commission)add('Comisiones · ventas seleccionadas',commission,false,{basis:commissions.reduce((sum,c)=>sum+c.total,0),factor:'1 %',units:commissions.length+' OP'});
  if(p.type==='COMISION'&&!commission)throw Error('Selecciona al menos una comisión pendiente.');
  if(['SALARIO','COMISION'].includes(p.type)){
    add('Aporte trabajador · salud 4 %',taxable*.04,true,{basis:taxable,factor:'4 %'});add('Aporte trabajador · pensión 4 %',taxable*.04,true,{basis:taxable,factor:'4 %'});
    if(taxable>=rates.salary*4)throw Error('Esta base alcanza cuatro salarios mínimos. Requiere revisión de aportes adicionales antes de emitir.');
    if(p.type==='SALARIO'&&taxable>rates.salary*2&&transport)throw Error('Revisa la procedencia del auxilio de transporte por el total devengado.');
  }
  if(p.type==='PRIMA'||p.type==='LIQUIDACION'){
    if(commissions.length)throw Error('Las comisiones se pagan en nómina o comprobante de comisiones.');
    if(p.reviewed!==true)throw Error('Revisa las bases, períodos y valores ya reconocidos.');
    const benefit=(concept,label,start,base,divisor,already)=>{
      payrollDate(start);if(start<employee.start||start>to)throw Error('Revisa el período de '+label.toLowerCase()+'.');
      const days=payrollDays(start,to);if(days>360)throw Error('Liquida '+label.toLowerCase()+' por vigencia anual.');
      base=payrollAmount(base);if(!base)throw Error('Falta la base de '+label.toLowerCase()+'.');const gross=Math.round(base*days/divisor),paid=payrollAmount(already);if(paid>gross)throw Error('Lo ya reconocido supera '+label.toLowerCase()+'.');
      add(label+' · '+days+' días',gross,false,{basis:base,factor:days+' / '+divisor+' días',from:start,to});add(label+' · ya reconocido',paid,true);cover(concept,start,to);return {gross,days};
    };
    const primaFrom=p.primaFrom||from;if(primaFrom.slice(0,4)!==to.slice(0,4)||Math.floor((Number(primaFrom.slice(5,7))-1)/6)!==Math.floor((Number(to.slice(5,7))-1)/6))throw Error('La prima debe corresponder a un mismo semestre.');
    benefit('PRIMA','Prima de servicios',primaFrom,p.benefitBase,360,p.primaPaid);
    if(p.type==='LIQUIDACION'){
      const c=benefit('CESANTIAS','Cesantías',p.severanceFrom||from,p.severanceBase||p.benefitBase,360,p.severancePaid);
      const interest=Math.round(c.gross*c.days*.12/360),interestPaid=payrollAmount(p.interestPaid);if(interestPaid>interest)throw Error('Revisa los intereses ya pagados.');add('Intereses a las cesantías',interest,false,{basis:c.gross,factor:'12 % × '+c.days+'/360'});add('Intereses ya pagados',interestPaid,true);
      benefit('VACACIONES','Vacaciones pendientes',p.vacationFrom||from,p.vacationBase,720,p.vacationPaid);
      if(payrollAmount(p.salaryPending)){const a=payrollDate(p.salaryPendingFrom),b=payrollDate(p.salaryPendingTo);if(a<employee.start||a>b||b>to||a.slice(0,7)!==b.slice(0,7))throw Error('Revisa las fechas del salario pendiente.');cover('SALARIO',a,b);}add('Salario pendiente de liquidación',p.salaryPending);add('Indemnización revisada',p.indemnity);
      const pending=payrollAmount(p.salaryPending);add('Salud sobre salario pendiente · 4 %',pending*.04,true,{basis:pending,factor:'4 %'});add('Pensión sobre salario pendiente · 4 %',pending*.04,true,{basis:pending,factor:'4 %'});
    }
  }
  add('Anticipos de nómina',p.advance,true);add('Otros descuentos autorizados',p.deduction,true);
  if((payrollAmount(p.deduction)||payrollAmount(p.extra)||payrollAmount(p.indemnity))&&!String(p.notes||'').trim())throw Error('Describe los conceptos adicionales y su soporte en las notas.');
  const earned=lines.filter(x=>!x.deduction).reduce((s,x)=>s+x.amount,0),deducted=lines.filter(x=>x.deduction).reduce((s,x)=>s+x.amount,0);
  if(deducted>earned||earned===0)throw Error('Revisa el neto: los descuentos no pueden superar lo devengado.');
  return {type:p.type,from,to,year,lines,earned,deducted,net:earned-deducted,coverage,commissions,rules:'CO-2026-09-v1',notes:String(p.notes||'').slice(0,500)};
}
