// Private append-only payroll ledger. No payroll action initiates a bank transfer.
var PAYROLL_HEADERS_=['ID','Fecha','Tipo','Entidad_ID','Version','Usuario','Request_ID','Fingerprint','Datos_JSON'];
function npSession_(ctx,permission){var s=validateSessionToken_(ctx.sessionToken,false);requirePermission_(s,'nomina.read');if(permission)requirePermission_(s,permission);return s;}
function npRows_(){return getSpreadsheet_().getSheetByName('Nomina_Eventos')?listRows_('Nomina_Eventos'):[];}
function npEnsure_(){var b=getSpreadsheet_(),s=b.getSheetByName('Nomina_Eventos');if(!s){s=b.insertSheet('Nomina_Eventos');s.getRange(1,1,1,PAYROLL_HEADERS_.length).setValues([PAYROLL_HEADERS_]);SpreadsheetApp.flush();}if(getHeaders_(s).join('|')!==PAYROLL_HEADERS_.join('|'))throw appError_('PAYROLL_SCHEMA','Revisa el registro de nómina.',503);}
function npState_(rows){var state={employees:{},receipts:{},files:{},settings:{},drafts:{}};rows.forEach(function(r){var d=parseJson_(r.Datos_JSON,null);if(!d)throw appError_('PAYROLL_INTEGRITY','Un registro de nómina necesita revisión.',409);var group=r.Tipo==='TRABAJADOR'?state.employees:r.Tipo==='ARCHIVO'?state.files:r.Tipo==='PARAMETROS'?state.settings:r.Tipo==='BORRADOR'?state.drafts:state.receipts;group[r.Entidad_ID]=d;});return state;}
function npText_(v,max){return String(v==null?'':v).trim().slice(0,max||160);}
function npReceipt_(st,id){var d=st.receipts[id];if(!d)throw appError_('PAYROLL_NOT_FOUND','No se encontró el comprobante.',404);return d;}
function npEmployee_(st,id){var e=st.employees[id];if(!e)throw appError_('PAYROLL_EMPLOYEE','Selecciona un trabajador registrado.',404);return e;}
function npCommissionRows_(st,userRows,orderRows){
  var reserved={};Object.values(st.receipts).filter(function(r){return r.status!=='ANULADO';}).forEach(function(r){(r.commissions||[]).forEach(function(c){if(reserved[c.order])throw appError_('PAYROLL_DUPLICATE','Hay una comisión repetida que requiere revisión.',409);reserved[c.order]={receipt:r,commission:c};});});
  var users={};(userRows||listRows_('Usuarios')).forEach(function(u){users[u.UID_Firebase]=u.Nombre_Completo;});
  return (orderRows||listRows_('Ordenes_Pedido')).filter(function(o){return o.Numero_OP;}).map(function(o){
    var held=reserved[o.Numero_OP],total=Number(o.Valor_Total),owner=String(o.Responsable||''),employees=Object.values(st.employees).filter(function(e){return e.sellerUid&&e.sellerUid===owner;});
    var cancelled=/ANUL|CANCEL/.test(normalizeCode_(o.Estado)),changed=held&&(held.commission.total!==total||cancelled||held.commission.owner!==owner);
    return {order:o.Numero_OP,date:valueDateIso_(o.Fecha),client:String(o.Nombre_Cliente||''),owner:owner,seller:users[owner]||owner||'Sin asesor',employeeId:employees.length===1?employees[0].id:'',total:total,paid:Number(o.Abonado_Total)||0,delivery:String(o.Estado_Entrega||o.Estado_Produccion||'Sin entrega registrada'),amount:Math.round(total/100),status:changed?'REVISAR':held?(held.receipt.status==='PAGADO'?'PAGADA':'EN_COMPROBANTE'):cancelled?'NO_APLICA':'PENDIENTE',receipt:held?held.receipt.number:'',reserved:!!held};
  }).sort(function(a,b){return a.date.localeCompare(b.date);});
}
function npList_(p,ctx){var s=npSession_(ctx),st=npState_(npRows_()),users=listRows_('Usuarios');return {employees:Object.values(st.employees),receipts:Object.values(st.receipts).map(function(r){return {id:r.id,number:r.number,employee:r.employee.name,type:r.type,from:r.from,to:r.to,status:r.status,net:r.net,date:r.date,revision:r.revision};}).sort(function(a,b){return b.date.localeCompare(a.date);}),commissions:npCommissionRows_(st,users),sellers:users.map(function(u){return {id:String(u.UID_Firebase||''),name:String(u.Nombre_Completo||'')};}).filter(function(u){return u.id;}),rates:npRates_(st),settings:Object.values(st.settings)};}
function npGet_(p,ctx){npSession_(ctx);var st=npState_(npRows_());if(p.employeeId){var e=npEmployee_(st,p.employeeId);return {employee:e,files:Object.values(st.files).filter(function(f){return f.employeeId===e.id;}).map(function(f){return {id:f.id,name:f.name,date:f.date};})};}return npReceipt_(st,p.id);}
function npPreviewData_(p,st,knownCommissions){
  var e=npEmployee_(st,p.employeeId);if(e.status!=='ACTIVO')throw Error('El trabajador está archivado.');
  var ids=p.orders||[];if(!Array.isArray(ids)||ids.length>40||new Set(ids).size!==ids.length)throw Error('Revisa la selección de ventas.');
  var all=ids.length?(Array.isArray(knownCommissions)?knownCommissions:npCommissionRows_(st)):[],commissions=ids.map(function(id){var c=all.filter(function(x){return x.order===id;})[0];if(!c||c.status!=='PENDIENTE'||c.employeeId!==e.id)throw Error('Una comisión ya está reservada, cambió o pertenece a otro trabajador.');return c;});
  var result=payrollCalculate(p,e,commissions,npRates_(st));result.employee=Object.assign({},e);result.employee.document=String(e.document);delete result.employee.contact;delete result.employee.address;delete result.employee.birthday;
  Object.values(st.receipts).filter(function(r){return r.status!=='ANULADO'&&r.employee.id===e.id;}).forEach(function(r){result.coverage.forEach(function(c){(r.coverage||[]).forEach(function(old){if(old.concept===c.concept&&old.from<=c.to&&old.to>=c.from)throw Error('El período de '+c.concept.toLowerCase()+' coincide con '+r.number+'. Revisa ese comprobante antes de emitir otro.');});});});
  return result;
}
function npPreview_(p,ctx){npSession_(ctx,'nomina.prepare');var d=npPreviewData_(p,npState_(npRows_()));return {document:d,fingerprint:sha256_(JSON.stringify(d))};}
function npCommit_(ctx,permission,type,make){
  var s=npSession_(ctx,permission),id=orderRequestId_(ctx.requestId),hash=sha256_(JSON.stringify(ctx.payrollPayload)),lock=osOperationLock_();if(!lock.tryLock(5000))throw appError_('PAYROLL_BUSY','Hay un guardado en curso. Reintenta el mismo registro.',503);
  try{var rows=npRows_(),old=rows.filter(function(r){return r.Request_ID===id;})[0];if(old){if(old.Usuario!==s.profile.uid||old.Fingerprint!==hash||old.Tipo!==type)throw appError_('REQUEST_ID_CONFLICT','El intento pertenece a otro contenido.',409);clearConfirmedOrderFence_();return parseJson_(old.Datos_JSON,null);}
    assertNoUnresolvedOrderFence_();var st=npState_(rows),d=make(st,s,rows);d.revision=(d.revision||0)+1;d.updatedAt=now_().toISOString();npEnsure_();
    var event={ID:Utilities.getUuid(),Fecha:d.updatedAt,Tipo:type,Entidad_ID:d.id,Version:d.revision,Usuario:s.profile.uid,Request_ID:id,Fingerprint:hash,Datos_JSON:JSON.stringify(d)};
    var audit={ID:id+'-AUD',Fecha:d.updatedAt,Usuario:s.profile.uid,Rol:s.profile.role,Modulo:'NOMINA',Accion:type,Entidad:'NOMINA',Entidad_ID:d.number||d.id,Resumen:'Actualización de nómina',Estado:'CONFIRMADA',Request_ID:id,Despues_JSON:JSON.stringify({status:d.status||'GUARDADO'}),Reversible:'NO',Motivo_No_Reversible:'Historial laboral conservado.'};
    // The same atomic batch supplies the global recovery fence with its confirmation.
    var requests=[orderAppendRequest_('Nomina_Eventos',[event]),orderAppendRequest_('Auditoria',[audit]),orderAppendRequest_('Idempotencia',[{Request_ID:id,Fecha:d.updatedAt,Tipo_Operacion:'NOMINA_'+type,Entidad:'NOMINA',Entidad_ID:d.id,Estado:'CONFIRMADA',Resultado_JSON:JSON.stringify({fingerprint:hash,result:{id:d.id,requestId:id}}),Usuario:s.profile.uid}])];
    SpreadsheetApp.flush();reserveOrderFence_(id,s.profile.uid,hash,'NOMINA_'+type);orderAtomicBatch_(requests);clearConfirmedOrderFence_();return d;
  }finally{lock.releaseLock();}
}
function npEmployeeSave_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,'nomina.workers','TRABAJADOR',function(st){
  var old=p.id?npEmployee_(st,p.id):null;if(old&&old.revision!==p.revision)throw Error('La ficha cambió. Vuelve a abrirla.');
  var e={id:old?old.id:'EMP-'+Utilities.getUuid(),revision:old?old.revision:0,name:npText_(p.name),document:npText_(p.document,40),role:npText_(p.role,80),branch:npText_(p.branch,8),start:payrollDate(p.start),end:p.end?payrollDate(p.end):'',birthday:p.birthday?payrollDate(p.birthday):'',contract:npText_(p.contract,60),contact:npText_(p.contact),address:npText_(p.address,300),salary:payrollAmount(p.salary),transport:p.transport!==false,sellerUid:npText_(p.sellerUid),status:p.status==='ARCHIVADO'?'ARCHIVADO':'ACTIVO'};
  if(!e.name||!e.document||!['MP','TP'].includes(e.branch)||!e.role||!e.contract)throw Error('Completa nombre, identificación, sede, cargo y contrato.');if(e.end&&e.end<e.start)throw Error('Revisa las fechas del contrato.');if(e.birthday&&e.birthday>=e.start)throw Error('Revisa la fecha de nacimiento.');
  if(e.salary&&e.salary<(npRates_(st)[Number(now_().toISOString().slice(0,4))]||PAYROLL_RATES[2026]).salary)throw Error('Para jornada completa, el salario no puede ser inferior al mínimo vigente.');
  if(Object.values(st.employees).some(function(x){return x.id!==e.id&&(x.document===e.document||e.sellerUid&&x.sellerUid===e.sellerUid);}))throw Error('La identificación o el asesor ya tiene una ficha laboral.');
  if(e.sellerUid&&!listRows_('Usuarios').some(function(u){return u.UID_Firebase===e.sellerUid;}))throw Error('Selecciona un asesor existente.');return e;
});}
function npIssue_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,'nomina.issue','EMISION',function(st,s){requirePermission_(s,'nomina.prepare');if(p.input._run){var run=p.input._run,draft=st.drafts[npDraftKey_(p.input.employeeId,run.month,run.half)];if((draft?draft.revision:0)!==Number(run.revision||0))throw Error('El borrador cambió. Vuelve a revisar la quincena.');}if(p.draftId){var draft=st.drafts[p.draftId];if(!draft||draft.employeeId!==p.input.employeeId||draft.revision!==p.draftRevision)throw Error('El borrador cambió. Vuelve a revisar la quincena.');}var d=npPreviewData_(p.input,st);if(sha256_(JSON.stringify(d))!==p.fingerprint)throw Error('Los datos cambiaron. Revisa nuevamente el cálculo.');if(p.confirmed!==true)throw Error('Confirma el desglose antes de emitir.');var n=Object.keys(st.receipts).length+1;d.id='NOM-'+Utilities.getUuid();d.number='NOM-'+String(n).padStart(5,'0');d.status='EMITIDO';d.date=now_().toISOString();d.issuedBy=s.profile.name;return d;});}
function npChange_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,p.operation==='PAGAR'?'nomina.pay':'nomina.issue','ESTADO',function(st,s){var d=JSON.parse(JSON.stringify(npReceipt_(st,p.id)));if(d.revision!==p.revision)throw Error('El comprobante cambió. Vuelve a abrirlo.');if(d.status!=='EMITIDO')throw Error('Solo puedes actualizar comprobantes emitidos pendientes de pago.');if(p.operation==='ANULAR'){if(!npText_(p.reason))throw Error('Indica el motivo de anulación.');d.status='ANULADO';d.reason=npText_(p.reason,500);}else if(p.operation==='PAGAR'){if(p.confirmed!==true)throw Error('Confirma que el pago ya fue realizado.');if(npCommissionRows_(st).some(function(c){return c.receipt===d.number&&c.status==='REVISAR';}))throw Error('La venta cambió. Anula el comprobante pendiente y revisa las comisiones antes de registrar el pago.');d.payment={date:payrollDate(p.date),method:npText_(p.method,40),reference:npText_(p.reference),by:s.profile.name};if(!['EFECTIVO','TRANSFERENCIA'].includes(d.payment.method))throw Error('Selecciona el medio de pago.');d.status='PAGADO';}else throw Error('Acción no válida.');return d;});}
function npPrivateFolder_(folder){var m=JSON.parse(mdDrive_('drive/v3/files/'+encodeURIComponent(folder.getId())+'?fields=trashed,shared,permissions(type,role)',{method:'get'}).getContentText());if(m.trashed||m.shared!==false||!m.permissions||m.permissions.length!==1||m.permissions[0].type!=='user'||m.permissions[0].role!=='owner')throw Error('La carpeta de nómina debe ser privada antes de guardar documentos laborales.');return folder;}
function npFolder_(employeeId,year){var parents=getDocumentsRoot_().getParents();if(!parents.hasNext())throw Error('No se encontró la raíz de Maderarte.');var root=parents.next();if(root.getName()!=='MADERARTE APP')throw Error('Revisa la raíz documental.');npPrivateFolder_(root);var folder=npPrivateFolder_(getOrCreateFolder_(root,'06_NOMINA'));var employee=npPrivateFolder_(getOrCreateFolder_(folder,sanitizeFolderName_(employeeId)));return npPrivateFolder_(getOrCreateFolder_(employee,year||'EXPEDIENTE'));}
function npFileSave_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,'nomina.workers','ARCHIVO',function(st){var e=npEmployee_(st,p.employeeId),bytes=Utilities.base64Decode(String(p.base64||''));if(bytes.length>650000||bytes.length<5||String.fromCharCode.apply(null,bytes.slice(0,5))!=='%PDF-')throw Error('Adjunta un PDF de hasta 650 KB.');var name=npText_(p.name,100).replace(/[^\w .áéíóúñÁÉÍÓÚÑ-]/g,'');if(!name.toLowerCase().endsWith('.pdf'))throw Error('Adjunta un archivo PDF.');var key='DOC-'+ctx.requestId,folder=npFolder_(e.id,''),existing=folder.getFilesByName(key+'.pdf'),f=existing.hasNext()?existing.next():folder.createFile(Utilities.newBlob(bytes,'application/pdf',key+'.pdf'));return {id:key,employeeId:e.id,fileId:f.getId(),name:name,date:now_().toISOString()};});}
function npFileRead_(p,ctx){npSession_(ctx);var st=npState_(npRows_()),f=st.files[p.id];if(!f)throw Error('No se encontró el documento.');return {name:f.name,base64:Utilities.base64Encode(DriveApp.getFileById(f.fileId).getBlob().getBytes())};}
function npPdfPlan_(p,ctx){npSession_(ctx);if(!ctx.proxyMeta.documentPipeline)throw Error('Solicitud documental no autorizada.');var d=npReceipt_(npState_(npRows_()),p.id);return {document:Object.assign({documentKind:'payroll'},d),hash:sha256_(JSON.stringify(d))};}
function npPdfSave_(p,ctx){npSession_(ctx);if(!ctx.proxyMeta.documentPipeline)throw Error('Solicitud documental no autorizada.');var lock=osOperationLock_();if(!lock.tryLock(5000))throw Error('Reintenta guardar el documento.');try{var d=npReceipt_(npState_(npRows_()),p.id);if(sha256_(JSON.stringify(d))!==p.hash)throw Error('El comprobante cambió. Genera su versión actual.');var bytes=Utilities.base64Decode(String(p.base64||''));if(bytes.length<5||bytes.length>12000000||String.fromCharCode.apply(null,bytes.slice(0,5))!=='%PDF-')throw Error('No se recibió un PDF válido.');var folder=npFolder_(d.employee.id,String(d.year)),name=d.number+'-v'+d.revision+'.pdf',existing=folder.getFilesByName(name);if(!existing.hasNext())folder.createFile(Utilities.newBlob(bytes,'application/pdf',name));return {saved:true,name:name};}finally{lock.releaseLock();}}

function npRates_(st){var rates=JSON.parse(JSON.stringify(PAYROLL_RATES));Object.values(st.settings||{}).forEach(function(x){rates[x.year]={salary:x.salary,transport:x.transport};});return rates;}
function npSettingsSave_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,'nomina.workers','PARAMETROS',function(st){
 var year=Number(p.year);if(!Number.isInteger(year)||year<2025||year>2100)throw Error('Revisa el año de los parámetros.');
 var id='RATES-'+year,old=st.settings[id];if(Number(p.revision||0)!==(old?old.revision:0))throw Error('Los parámetros cambiaron. Actualiza y revisa antes de guardar.');
 var salary=payrollAmount(p.salary),transport=payrollAmount(p.transport);if(!salary)throw Error('Indica el salario mínimo mensual.');
 if(PAYROLL_RATES[year]&&(salary<PAYROLL_RATES[year].salary||transport<PAYROLL_RATES[year].transport))throw Error('Los valores no pueden ser inferiores a la referencia legal verificada para ese año.');
 if(p.confirmed!==true)throw Error('Confirma los parámetros salariales.');
 return {id:id,revision:old?old.revision:0,year:year,salary:salary,transport:transport};
 });}
function npDraftKey_(employeeId,month,half){payrollPeriod(month,half);return 'DRAFT-'+employeeId+'-'+month+'-'+half;}
function npRunInput_(e,month,half){var period=payrollPeriod(month,half),from=e.start>period.from?e.start:period.from,to=e.end&&e.end<period.to?e.end:period.to;return {type:'SALARIO',employeeId:e.id,from:from,to:to,absent:0,orders:[]};}
function npPeriod_(p,ctx){npSession_(ctx);var period=payrollPeriod(p.month,p.half),st=npState_(npRows_()),allCommissions=null,items=Object.values(st.employees).filter(function(e){return e.start<=period.to&&(!e.end||e.end>=period.from)&&(e.status==='ACTIVO'||!!e.end);}).map(function(e){
 var draft=st.drafts[npDraftKey_(e.id,p.month,p.half)],input=draft?draft.input:npRunInput_(e,p.month,p.half),docs=Object.values(st.receipts).filter(function(r){return r.status!=='ANULADO'&&r.employee.id===e.id&&(r.coverage||[]).some(function(c){return c.concept==='SALARIO'&&c.from<=period.to&&c.to>=period.from;});});
 var row={employee:{id:e.id,name:e.name,role:e.role,branch:e.branch},input:input,draft:draft||null,status:draft?'BORRADOR':'POR_REVISAR',net:null,receipts:docs.map(function(r){return {id:r.id,number:r.number,status:r.status,net:r.net,from:r.from,to:r.to};})};
 if(docs.length){row.status=docs.every(function(r){return r.status==='PAGADO';})?'PAGADO':'EMITIDO';row.net=docs.reduce(function(sum,r){return sum+r.net;},0);row.partial=docs.length!==1||docs[0].from!==input.from||docs[0].to!==input.to;if(row.partial)row.status='PARCIAL';return row;}
 try{if((input.orders||[]).length&&!allCommissions)allCommissions=npCommissionRows_(st);var d=npPreviewData_(input,st,allCommissions);row.net=d.net;row.days=d.attendance;row.fingerprint=sha256_(JSON.stringify(d));if(draft&&draft.status==='REVISADO'&&draft.fingerprint===row.fingerprint)row.status='REVISADO';else if(draft&&draft.status==='REVISADO')row.message='Cambió la información. Revisa nuevamente antes de pagar.';}catch(err){row.message=String(err.message||err);row.status='REVISAR_DATOS';}return row;
 });return {month:p.month,half:String(p.half),from:period.from,to:period.to,label:payrollPeriodLabel('SALARIO',period.from,period.to),items:items};}
function npDraftSave_(p,ctx){ctx.payrollPayload=p;return npCommit_(ctx,'nomina.prepare','BORRADOR',function(st,s){
 var e=npEmployee_(st,p.input&&p.input.employeeId),period=payrollPeriod(p.month,p.half),id=npDraftKey_(e.id,p.month,p.half),old=st.drafts[id];if(Number(p.revision||0)!==(old?old.revision:0))throw Error('Otra persona actualizó este borrador. Abre de nuevo la quincena.');
 var input=JSON.parse(JSON.stringify(p.input)),expected=npRunInput_(e,p.month,p.half);if(input.from!==expected.from||input.to!==expected.to)throw Error('Revisa las fechas de vinculación y vuelve a abrir la quincena.');if(input.type!=='SALARIO'||input.from<period.from||input.to>period.to)throw Error('El borrador debe corresponder a esta quincena.');
 var d=npPreviewData_(input,st),fingerprint=sha256_(JSON.stringify(d));if(p.reviewed===true&&p.fingerprint!==fingerprint)throw Error('El cálculo cambió. Revisa nuevamente los valores.');
 return {id:id,revision:old?old.revision:0,month:p.month,half:String(p.half),employeeId:e.id,input:input,status:p.reviewed===true?'REVISADO':'BORRADOR',fingerprint:fingerprint,net:d.net,reviewedBy:p.reviewed===true?s.profile.name:'',reviewedAt:p.reviewed===true?now_().toISOString():''};
 });}
