from pathlib import Path
root = Path('.')
def edit(path, old, new, count=None):
    p=root/path; s=p.read_text(); n=s.count(old)
    if not n or count is not None and n != count: raise ValueError((path,n,old[:75]))
    p.write_text(s.replace(old,new))
edit('apps-script/Config.gs',"  var value = String(getScriptProperties_().getProperty(name) || '').trim();\n  if (!value)","  var scoped = typeof osScopedProperty_ === 'function' ? osScopedProperty_(name) : null;\n  var value = scoped === null ? String(getScriptProperties_().getProperty(name) || '').trim() : String(scoped || '');\n  if (!value)",1)
edit('apps-script/SheetHelpers.gs','  var sheet = getSpreadsheet_().getSheetByName(name);',"  var authSheet = typeof osAuthSheet_ === 'function' ? osAuthSheet_(name) : null;\n  var sheet = authSheet || getSpreadsheet_().getSheetByName(name);",1)
edit('apps-script/OrderCreationRecovery.gs',"var ORDER_CREATION_FENCE_KEY_ = 'ORDER_CREATION_PENDING';", "var ORDER_CREATION_FENCE_KEY_ = 'ORDER_CREATION_PENDING';\nfunction orderFenceKey_() { return typeof osFenceKey_ === 'function' ? osFenceKey_() : ORDER_CREATION_FENCE_KEY_; }",1)
p=root/'apps-script/OrderCreationRecovery.gs';s=p.read_text();s=s.replace('(ORDER_CREATION_FENCE_KEY_', '(orderFenceKey_()');p.write_text(s)
p=root/'apps-script/OrderCreation.gs';s=p.read_text()
old="if (!MADERARTE_APP.COMMERCIAL_WRITES || getConfigValue_('MODO_OPERACION', 'PREPARACION') !== 'OPERACION' || optionalProperty_('ORDER_SAVE_ENABLED', 'NO') !== 'SI')"
assert s.count(old)==2
s=s.replace(old,"if (!(typeof osActive_ === 'function' && osActive_()) && (!MADERARTE_APP.COMMERCIAL_WRITES || getConfigValue_('MODO_OPERACION', 'PREPARACION') !== 'OPERACION' || optionalProperty_('ORDER_SAVE_ENABLED', 'NO') !== 'SI'))")
s=s.replace('var lock = LockService.getScriptLock();',"var lock = typeof osOperationLock_ === 'function' ? osOperationLock_() : LockService.getScriptLock();")
s=s.replace("if (getSpreadsheet_().getName() !== MADERARTE_APP.SPREADSHEET_NAME)","if (getSpreadsheet_().getName() !== (typeof osDatabaseName_ === 'function' ? osDatabaseName_() : MADERARTE_APP.SPREADSHEET_NAME))")
s=s.replace("    var fingerprint = sha256_(JSON.stringify(draft));", "    if (typeof osValidateDraft_ === 'function') osValidateDraft_(draft, requestId);\n    var fingerprint = sha256_(JSON.stringify(draft));")
s=s.replace('    reserveOrderFence_(requestId, session.profile.uid, fingerprint);',"    if (typeof osReserveOrder_ === 'function') osReserveOrder_(requestId);\n    reserveOrderFence_(requestId, session.profile.uid, fingerprint);")
s=s.replace("  var ready = typeof mdConfigured_", "  var sandbox = typeof osActive_ === 'function' && osActive_();\n  var ready = typeof mdConfigured_")
s=s.replace("&& optionalProperty_('ORDER_DOCUMENTS_ACCEPTED', 'NO') === 'SI';", "&& (sandbox || optionalProperty_('ORDER_DOCUMENTS_ACCEPTED', 'NO') === 'SI');")
s=s.replace("  var enabled = ready && MADERARTE_APP.COMMERCIAL_WRITES", "  var enabled = ready && (sandbox ? !OWNER_SANDBOX_CONTEXT_.requestId && countRows_('Ordenes_Pedido') === 0 : MADERARTE_APP.COMMERCIAL_WRITES")
s=s.replace("&& optionalProperty_('ORDER_SAVE_ENABLED', 'NO') === 'SI' && optionalProperty_('ORDER_DOCUMENTS_ENABLED', 'NO') === 'SI';", "&& optionalProperty_('ORDER_SAVE_ENABLED', 'NO') === 'SI' && optionalProperty_('ORDER_DOCUMENTS_ENABLED', 'NO') === 'SI');")
p.write_text(s)
p=root/'apps-script/OrderMedia.gs';s=p.read_text()
s=s.replace('var lock = LockService.getScriptLock();',"var lock = typeof osOperationLock_ === 'function' ? osOperationLock_() : LockService.getScriptLock();")
s=s.replace("if (!MADERARTE_APP.COMMERCIAL_WRITES || getConfigValue_('MODO_OPERACION', 'PREPARACION') !== 'OPERACION' || optionalProperty_('ORDER_DOCUMENTS_ENABLED', 'NO') !== 'SI')", "if (!(typeof osActive_ === 'function' && osActive_()) && (!MADERARTE_APP.COMMERCIAL_WRITES || getConfigValue_('MODO_OPERACION', 'PREPARACION') !== 'OPERACION' || optionalProperty_('ORDER_DOCUMENTS_ENABLED', 'NO') !== 'SI'))")
s=s.replace("  // items contain descriptions", "  if (typeof osActive_ === 'function' && osActive_()) publicData.sandbox = OWNER_SANDBOX_CONTEXT_.id;\n  // items contain descriptions")
p.write_text(s)
p=root/'apps-script/OrderSandbox.gs';s=p.read_text();s=s.replace("  if (!s.requestId) { s.requestId = requestId; osStore_(s); }\n",'');s=s.replace('function osCleanupPlan_(s) {',"function osReserveOrder_(requestId) {\n  if (!osActive_()) return;\n  var s = OWNER_SANDBOX_CONTEXT_;\n  if (!s.requestId) { s.requestId = requestId; osStore_(s); }\n}\nfunction osCleanupPlan_(s) {")
p.write_text(s)
p=root/'apps-script/Router.gs';s=p.read_text();s=s.replace("    case 'SISTEMA_ESTADO':", "    case 'PRUEBA_ESTADO': return osStatus_(context);\n    case 'PRUEBA_INICIAR': return osStart_(payload, context);\n    case 'PRUEBA_LIMPIAR': return osClean_(payload, context);\n    case 'SISTEMA_ESTADO':")
s=s.replace("    var data = routeAction_(action, body.payload && typeof body.payload === 'object' ? body.payload : {}, context);", "    var run = function() { return routeAction_(action, body.payload && typeof body.payload === 'object' ? body.payload : {}, context); };\n    var data = Object.prototype.hasOwnProperty.call(body, 'sandboxId') ? osAdmit_(body.sandboxId, action, context, run) : run();")
p.write_text(s)
p=root/'functions/api/maderarte.js';s=p.read_text();s=s.replace("    appVersion: String(body?.appVersion || ''),", "    appVersion: String(body?.appVersion || ''),\n    ...(Object.hasOwn(body || {}, 'sandboxId') ? { sandboxId: body.sandboxId } : {}),")
s=s.replace("internal || action === 'ORDEN_FOTO_GUARDAR' ? 60000 : UPSTREAM_TIMEOUT_MS", "internal || body?.sandboxId || action.startsWith('PRUEBA_') || action === 'ORDEN_FOTO_GUARDAR' ? 90000 : UPSTREAM_TIMEOUT_MS")
s=s.replace("{ action: internalAction, payload }, requestId, true", "{ action: internalAction, payload, ...(Object.hasOwn(body || {}, 'sandboxId') ? { sandboxId: body.sandboxId } : {}) }, requestId, true")
p.write_text(s)
